#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

alias hostip="curl ip.appspot.com; echo"

# set locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# add NAO Python SDK to path
export PYTHONPATH="${PYTHONPATH}:$HOME/pynaoqi"
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:$HOME/pynaoqi"

# add Go to the path
export PATH="$PATH:/usr/local/opt/go/libexec/bin:/~/gocode/bin"
export GOPATH=~/gocode

# enable Shims and Autocompletion
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
if which jenv > /dev/null; then eval "$(jenv init -)"; fi
fpath=(/usr/local/share/zsh-completions $fpath)
